import { Component, OnInit, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { CommunityProjectDocument, CommunityProjectStatus } from '../../../../core/firebase/models/firestore-data.models';
import { CommunityProjectAdminService } from './community-project-admin.service';

@Component({ selector: 'app-community-project-editor', standalone: true, imports: [ReactiveFormsModule, RouterLink], templateUrl: './community-project-editor.component.html', styleUrl: './community-project-editor.component.scss' })
export class CommunityProjectEditorComponent implements OnInit {
  readonly loading = signal(false); readonly saving = signal(false); readonly error = signal(''); private existing?: CommunityProjectDocument;
  private readonly fb = inject(FormBuilder);
  readonly form = this.fb.nonNullable.group({ slug: ['', [Validators.required, Validators.pattern(/^[a-z0-9]+(?:-[a-z0-9]+)*$/)]], title: ['', Validators.required], summary: ['', Validators.required], content: ['', Validators.required], category: ['', Validators.required], status: ['planned' as CommunityProjectStatus, Validators.required], progress: [0, [Validators.required, Validators.min(0), Validators.max(100), Validators.pattern(/^\d+$/)]], startDate: [''], completionDate: [''], imageUrl: ['', Validators.required], imageAlt: ['', Validators.required], imageCaption: [''], featured: [false] });
  constructor(private readonly route: ActivatedRoute, private readonly router: Router, private readonly admin: CommunityProjectAdminService) {}
  async ngOnInit(): Promise<void> { const id = this.route.snapshot.paramMap.get('id'); if (!id) return; this.loading.set(true); try { const project = await this.admin.get(id); if (!project) throw new Error('Community project not found.'); this.existing = project; this.form.patchValue({ ...project, startDate: project.startDate ?? '', completionDate: project.completionDate ?? '', imageUrl: project.image.url, imageAlt: project.image.altText, imageCaption: project.image.caption ?? '' }); } catch (error) { this.error.set(error instanceof Error ? error.message : 'Project could not be loaded.'); } finally { this.loading.set(false); } }
  async save(): Promise<void> { this.form.markAllAsTouched(); if (this.form.invalid) { this.error.set('Complete all required fields and use a progress value from 0 to 100.'); return; } this.saving.set(true); this.error.set(''); const value = this.form.getRawValue(); try { await this.admin.save({ slug: value.slug.trim(), title: value.title.trim(), summary: value.summary.trim(), content: value.content.trim(), category: value.category.trim(), status: value.status, progress: Number(value.progress), featured: value.featured, ...(value.startDate ? { startDate: value.startDate } : {}), ...(value.completionDate ? { completionDate: value.completionDate } : {}), image: { url: value.imageUrl.trim(), altText: value.imageAlt.trim(), ...(value.imageCaption.trim() ? { caption: value.imageCaption.trim() } : {}) } }, this.existing); await this.router.navigateByUrl('/admin/projects'); } catch (error) { this.error.set(error instanceof Error ? error.message : 'Project could not be saved.'); } finally { this.saving.set(false); } }
}
