import { ContractorDocument } from '../../../core/firebase/models/firestore-data.models';
import { FirestoreDataService } from '../../../core/firebase/services/firestore-data.service';
import { AuthService } from '../../auth/services/auth.service';
import { ContractorRepository, isDirectoryContractor } from './contractor.repository';
const profile = (extra: Partial<ContractorDocument> = {}): ContractorDocument => ({ id: 'owner', userId: 'owner', fullName: 'Owner', businessName: 'Co', categoryIds: [], services: [], serviceAreas: [], rating: 4, reviewCount: 9, verified: true, status: 'active', approvalStatus: 'approved', profileVisibility: 'public', jobAvailability: 'available', contactPreferences: { preferredMethod: 'platform' }, portfolioMedia: [], createdAt: 'then', updatedAt: 'then', ...extra });
describe('ContractorRepository', () => {
 it('requires every moderation predicate for directory visibility', () => { expect(isDirectoryContractor(profile())).toBeTrue(); expect(isDirectoryContractor(profile({ status: 'deactivated' }))).toBeFalse(); expect(isDirectoryContractor(profile({ approvalStatus: 'rejected' }))).toBeFalse(); expect(isDirectoryContractor(profile({ profileVisibility: 'hidden' }))).toBeFalse(); });
 it('preserves ownership and read-only trust fields on update', async () => { const existing = profile(); const upsert = jasmine.createSpy().and.callFake(async (x: ContractorDocument) => x); const data = { contractors: { getById: async () => existing, upsert } } as unknown as FirestoreDataService; const auth = { authUser: () => ({ id: 'owner', idToken: 'token' }) } as AuthService; const repo = new ContractorRepository(data, auth); await repo.updateOwnedProfile({ businessName: 'New', bio: '', categoryIds: [], services: ['Repair'], serviceAreas: [], profileVisibility: 'public', jobAvailability: 'available', contactPreferences: { preferredMethod: 'platform' }, portfolioMedia: [] }); const saved = upsert.calls.mostRecent().args[0]; expect(saved.userId).toBe('owner'); expect(saved.rating).toBe(4); expect(saved.reviewCount).toBe(9); expect(saved.verified).toBeTrue(); expect(saved.approvalStatus).toBe('approved'); });
 it('rejects edits from rejected or deactivated owners', async () => { for (const existing of [profile({ approvalStatus: 'rejected' }), profile({ status: 'deactivated' })]) { const data = { contractors: { getById: async () => existing } } as unknown as FirestoreDataService; const repo = new ContractorRepository(data, { authUser: () => ({ id: 'owner', idToken: 'token' }) } as AuthService); await expectAsync(repo.updateOwnedProfile({ businessName: '', bio: '', categoryIds: [], services: [], serviceAreas: [], profileVisibility: 'hidden', jobAvailability: 'unavailable', contactPreferences: { preferredMethod: 'platform' }, portfolioMedia: [] })).toBeRejected(); } });
});
