import { Component, OnInit, inject, signal } from '@angular/core';
import { ReactiveFormsModule, FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { CommitteeMemberDocument } from '../../../../core/firebase/models/firestore-data.models';
import { CommitteeAdminService } from './committee-admin.service';

@Component({selector:'app-committee-member-editor',standalone:true,imports:[ReactiveFormsModule,RouterLink],template:`<section><a routerLink="/admin/committee">← Committee</a><h1>{{ existing ? 'Edit' : 'Add' }} committee member</h1>
@if(error()){<p role="alert">{{error()}}</p>}<form [formGroup]="form" (ngSubmit)="save()"><label>Name<input formControlName="name"></label><label>Stable slug<input formControlName="slug"></label><label>Role/title<input formControlName="role"></label><label>Description<textarea formControlName="description"></textarea></label><label>Display order<input type="number" formControlName="displayOrder"></label><label>Image URL<input formControlName="imageUrl"></label><label>Image alt text<input formControlName="imageAlt"></label><label>Publication<select formControlName="publicationState"><option value="draft">Draft</option><option value="published">Published</option></select></label><button [disabled]="saving()">Save</button></form></section>`,styles:[`form{display:grid;gap:1rem;max-width:45rem}label{display:grid;gap:.3rem}`]})
export class CommitteeMemberEditorComponent implements OnInit { private fb=inject(FormBuilder); existing?:CommitteeMemberDocument; error=signal('');saving=signal(false);form=this.fb.nonNullable.group({name:['',Validators.required],slug:['',[Validators.required,Validators.pattern(/^[a-z0-9]+(?:-[a-z0-9]+)*$/)]],role:['',Validators.required],description:['',Validators.required],displayOrder:[0,Validators.required],imageUrl:[''],imageAlt:[''],publicationState:['draft' as 'draft'|'published',Validators.required]});constructor(private route:ActivatedRoute,private router:Router,private admin:CommitteeAdminService){}async ngOnInit(){const id=this.route.snapshot.paramMap.get('id');if(id){this.existing=(await this.admin.get(id))??undefined;if(!this.existing){this.error.set('Committee member not found.');return;}this.form.patchValue({...this.existing,imageUrl:this.existing.image?.url??'',imageAlt:this.existing.image?.altText??''});}}async save(){if(this.form.invalid)return this.error.set('Complete all required fields.');this.saving.set(true);const v=this.form.getRawValue();try{await this.admin.save({name:v.name.trim(),slug:v.slug.trim(),role:v.role.trim(),description:v.description.trim(),displayOrder:v.displayOrder,publicationState:v.publicationState,...(v.imageUrl.trim()?{image:{url:v.imageUrl.trim(),altText:v.imageAlt.trim()}}:{})},this.existing);await this.router.navigateByUrl('/admin/committee');}catch(e){this.error.set(e instanceof Error?e.message:'Could not save.');}finally{this.saving.set(false);}}}
